version: "3.9"

services:

  db:
    image: mysql:8
    container_name: hr360-db
    restart: always
    env_file:
      - .env
    ports:
      - "3312:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./Backend Project
      dockerfile: Dockerfile
    container_name: hr360-backend
    command: gunicorn hrms.wsgi:application --bind 0.0.0.0:8000
    env_file:                 # ðŸ”¥ THIS WAS MISSING
      - .env
    volumes:
      - ./Backend Project:/app
      - ./Backend Project/staticfiles:/app/staticfiles
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: hr360-nginx
    ports:
      - "8878:80"
    volumes:
      - ./Backend Project/staticfiles:/staticfiles
      - ./default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

volumes:
  dbdata:

