version: "3.9"

services:

  db:
    image: mysql:8
    container_name: hr360-db
    restart: always
    env_file:
      - .env
    ports:
      - "3312:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./Backend Project
      dockerfile: Dockerfile
    container_name: hr360-backend
    command: gunicorn hrms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Backend Project:/app
      - ./Backend Project/staticfiles:/app/staticfiles
    ports:
      - "8877:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: hr360-nginx
    ports:
      - "8878:80"
    volumes:
      # Mount collected static files
      - ./Backend Project/staticfiles:/staticfiles
      # Use our custom nginx config
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  dbdata:
